import type { Metadata } from "next";
import { JetBrains_Mono, Roboto_Serif, Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/Utils/sessionprovider";

// Fonts
const robotoSerif = Roboto_Serif({
  subsets: ["latin"],
  weight: ["400"], // only the weight you need
  variable: "--font-robotoSerif",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400"], // only the weight you need
  variable: "--font-jetbrainsMono",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400"], // only the weight you need
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "T-Monowar",
  description: "Generated by Tarek Monowar",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${robotoSerif.variable} ${inter.variable} `}
      >
        {" "}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
